/**
  ******************************************************************************
  * @file    SystemClock.h
  * @author  Generated by the STM32CubeMX
  * @brief   Clock configuration for the stm32f746g-disco
  *
  *          The file contains ::
  *           + Function protoypes
  *
  ******************************************************************************
  */

#ifndef SYSTEM_CLOCK_H
#define SYSTEM_CLOCK_H

void SystemClock_Config(void);
void Error_Handler(void);

#endif
